pipeline:
    name: deploy
    identifier: deploy
    projectIdentifier: harnessciecgouteix
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: deploy
              identifier: deploy
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: myservice
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: account.bootcampdockerhub
                                          imagePath: nikpap/payment-service
                                          tag: tophfr-latest
                                      type: DockerRegistry
                              manifests:
                                  - manifest:
                                        identifier: myman
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: xxx
                                                    gitFetchType: Branch
                                                    paths:
                                                        - /harness-deploy/values.yaml
                                                    repoName: harness-cie-lab
                                                    branch: main
                  infrastructure:
                      environmentRef: myenv
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.bootcampgkecluster
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
